### ISSUE TITLE
After using the template, cloning, going to any app directory, example: cd vue-app, then running npm install, npm run serve

### ISSUE THREAD

**Issue by jcpachkoski** [johnpapa/shopathome#178]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (C:\shopathome\vue-app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\shopathome\vue-app\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\shopathome\vue-app\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\shopathome\vue-app\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\shopathome\vue-app\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\shopathome\vue-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\shopathome\vue-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\shopathome\vue-app\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\shopathome\vue-app\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\shopathome\vue-app\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\shopathome\vue-app\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by johnpapa** [comment]
Thanks for reporting this! This was likely a transient dependency issue. If you're still seeing problems, please open a fresh issue with the error output and we'll take a look. 🙏
